In [15]:
import pandas as pd
import re

In [31]:
# read data of values only. Removed % during data cleaning to format to float
raw = pd.read_csv('Data/QUANT_DS_A_16.csv')
raw.head()

,Patient 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,0.00,0.11,0.05,0.00,0.10,0.00,0.05,0.00,0.11,0.04,0.03,0.00,0.00,0.0,0.1
1,0.0,0.00,0.11,0.11,0.04,0.09,0.04,0.05,0.05,0.03,0.08,0.03,0.06,0.00,0.0,0.1
2,0.0,0.06,0.11,0.00,0.17,0.09,0.20,0.09,0.00,0.00,0.09,0.12,0.00,0.09,0.0,0.2
3,0.0,0.00,0.11,0.00,0.00,0.09,0.04,0.03,0.05,0.00,0.06,0.12,0.00,0.00,0.0,0.1
4,0.0,0.06,0.11,0.05,0.17,0.09,0.20,0.04,0.00,0.00,0.08,0.12,0.00,0.17,0.0,0.2

In [30]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6171 entries, 0 to 6170
Data columns (total 16 columns):
Patient 1    6160 non-null float64
2            6164 non-null float64
3            6166 non-null float64
4            6151 non-null float64
5            6171 non-null float64
6            6158 non-null float64
7            6168 non-null float64
8            6171 non-null float64
9            6087 non-null float64
10           6168 non-null float64
11           6168 non-null float64
12           6166 non-null float64
13           6160 non-null float64
14           6156 non-null float64
15           6171 non-null float64
16           6158 non-null float64
dtypes: float64(16)
memory usage: 771.5 KB

In [50]:
# Nans detected. Assuming Nans are 0. Otherwise will have to drop values
raw.fillna(0, inplace=True)

In [51]:
# transpose the data. While region, position, gene are important information, it is not needed at the moment
df = raw.T

In [52]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,6161,6162,6163,6164,6165,6166,6167,6168,6169,6170
Patient 1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.66,3.97,3.31,5.96,5.96,1.99,4.64,3.97
2,0.00,0.00,0.06,0.00,0.06,0.00,0.05,0.00,0.05,0.00,...,0.38,0.77,0.39,0.40,0.81,0.42,0.85,0.86,0.87,0.87
3,0.11,0.11,0.11,0.11,0.11,0.00,0.11,0.11,0.21,0.16,...,1.19,1.44,1.25,0.38,1.17,1.34,1.37,1.53,1.41,1.43
4,0.05,0.11,0.00,0.00,0.05,0.00,0.00,0.00,0.00,0.05,...,1.29,2.05,2.06,0.63,1.96,1.75,2.02,2.23,2.02,2.11
5,0.00,0.04,0.17,0.00,0.17,0.04,0.17,0.00,0.04,0.00,...,0.87,2.41,1.99,1.21,2.03,0.96,2.16,2.28,2.25,2.14

In [56]:
# add in labels, who has disease a, b, c and who are not affected
df['label'] = [1, 1, 3, 3, 1, 3, 1, 0, 0, 0, 0, 0, 2, 2, 3, 2]
df

,0,1,2,3,4,5,6,7,8,9,...,6162,6163,6164,6165,6166,6167,6168,6169,6170,label
Patient 1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.66,3.97,3.31,5.96,5.96,1.99,4.64,3.97,1
2,0.00,0.00,0.06,0.00,0.06,0.00,0.05,0.00,0.05,0.00,...,0.77,0.39,0.40,0.81,0.42,0.85,0.86,0.87,0.87,1
3,0.11,0.11,0.11,0.11,0.11,0.00,0.11,0.11,0.21,0.16,...,1.44,1.25,0.38,1.17,1.34,1.37,1.53,1.41,1.43,3
4,0.05,0.11,0.00,0.00,0.05,0.00,0.00,0.00,0.00,0.05,...,2.05,2.06,0.63,1.96,1.75,2.02,2.23,2.02,2.11,3
5,0.00,0.04,0.17,0.00,0.17,0.04,0.17,0.00,0.04,0.00,...,2.41,1.99,1.21,2.03,0.96,2.16,2.28,2.25,2.14,1
6,0.10,0.09,0.09,0.09,0.09,0.19,0.28,0.09,0.18,0.09,...,0.57,0.53,1.59,1.06,1.06,1.06,1.06,1.06,1.60,3
7,0.00,0.04,0.20,0.04,0.20,0.00,0.20,0.00,0.08,0.00,...,1.37,1.06,0.47,0.96,0.56,1.21,1.08,1.24,1.25,1
8,0.05,0.05,0.09,0.03,0.04,0.00,0.04,0.02,0.06,0.03,...,1.42,1.17,0.42,1.01,0.84,1.33,1.24,1.33,1.38,0
9,0.00,0.05,0.00,0.05,0.00,0.05,0.00,0.00,0.00,0.00,...,37.19,27.10,26.88,1.18,26.92,1.25,29.45,28.15,28.77,0
10,0.11,0.03,0.00,0.00,0.00,0.03,0.03,0.00,0.03,0.00,...,0.51,0.52,2.36,1.57,3.15,2.37,1.06,2.11,2.37,0
11,0.04,0.08,0.09,0.06,0.08,0.04,0.12,0.03,0.10,0.06,...,39.45,29.97,28.87,2.31,28.31,2.78,31.71,29.78,31.43,0
12,0.03,0.03,0.12,0.12,0.12,0.03,0.15,0.06,0.06,0.06,...,2.15,1.73,0.64,1.93,1.32,1.85,1.87,2.07,1.91,0
13,0.00,0.06,0.00,0.00,0.00,0.06,0.00,0.00,0.00,0.06,...,1.81,1.38,0.26,1.42,1.06,1.08,1.50,1.25,1.42,2
14,0.00,0.00,0.09,0.00,0.17,0.00,0.08,0.00,0.08,0.00,...,1.12,1.02,0.11,1.16,1.18,1.20,1.21,1.10,0.99,2
15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,1.72,1.64,0.75,1.52,0.94,1.75,1.78,1.48,2.01,3
16,0.10,0.10,0.20,0.10,0.20,0.00,0.30,0.10,0.10,0.10,...,0.00,0.00,1.33,1.33,1.33,1.33,0.00,1.33,1.33,2

In [61]:
df.iloc[:, :6171]

,0,1,2,3,4,5,6,7,8,9,...,6161,6162,6163,6164,6165,6166,6167,6168,6169,6170
Patient 1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.66,3.97,3.31,5.96,5.96,1.99,4.64,3.97
2,0.00,0.00,0.06,0.00,0.06,0.00,0.05,0.00,0.05,0.00,...,0.38,0.77,0.39,0.40,0.81,0.42,0.85,0.86,0.87,0.87
3,0.11,0.11,0.11,0.11,0.11,0.00,0.11,0.11,0.21,0.16,...,1.19,1.44,1.25,0.38,1.17,1.34,1.37,1.53,1.41,1.43
4,0.05,0.11,0.00,0.00,0.05,0.00,0.00,0.00,0.00,0.05,...,1.29,2.05,2.06,0.63,1.96,1.75,2.02,2.23,2.02,2.11
5,0.00,0.04,0.17,0.00,0.17,0.04,0.17,0.00,0.04,0.00,...,0.87,2.41,1.99,1.21,2.03,0.96,2.16,2.28,2.25,2.14
6,0.10,0.09,0.09,0.09,0.09,0.19,0.28,0.09,0.18,0.09,...,0.26,0.57,0.53,1.59,1.06,1.06,1.06,1.06,1.06,1.60
7,0.00,0.04,0.20,0.04,0.20,0.00,0.20,0.00,0.08,0.00,...,0.58,1.37,1.06,0.47,0.96,0.56,1.21,1.08,1.24,1.25
8,0.05,0.05,0.09,0.03,0.04,0.00,0.04,0.02,0.06,0.03,...,0.58,1.42,1.17,0.42,1.01,0.84,1.33,1.24,1.33,1.38
9,0.00,0.05,0.00,0.05,0.00,0.05,0.00,0.00,0.00,0.00,...,0.52,37.19,27.10,26.88,1.18,26.92,1.25,29.45,28.15,28.77
10,0.11,0.03,0.00,0.00,0.00,0.03,0.03,0.00,0.03,0.00,...,0.09,0.51,0.52,2.36,1.57,3.15,2.37,1.06,2.11,2.37
11,0.04,0.08,0.09,0.06,0.08,0.04,0.12,0.03,0.10,0.06,...,0.56,39.45,29.97,28.87,2.31,28.31,2.78,31.71,29.78,31.43
12,0.03,0.03,0.12,0.12,0.12,0.03,0.15,0.06,0.06,0.06,...,1.30,2.15,1.73,0.64,1.93,1.32,1.85,1.87,2.07,1.91
13,0.00,0.06,0.00,0.00,0.00,0.06,0.00,0.00,0.00,0.06,...,0.95,1.81,1.38,0.26,1.42,1.06,1.08,1.50,1.25,1.42
14,0.00,0.00,0.09,0.00,0.17,0.00,0.08,0.00,0.08,0.00,...,1.00,1.12,1.02,0.11,1.16,1.18,1.20,1.21,1.10,0.99
15,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.85,1.72,1.64,0.75,1.52,0.94,1.75,1.78,1.48,2.01
16,0.10,0.10,0.20,0.10,0.20,0.00,0.30,0.10,0.10,0.10,...,0.00,0.00,0.00,1.33,1.33,1.33,1.33,0.00,1.33,1.33

In [66]:
x = df.iloc[:, :6171]
y = df.iloc[:, 6171]

# use random forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [65]:
score

array([0.57142857, 0.4       , 0.25      ])